package engine

import (
	"encoding/json"
	"fmt"
	"image"
	"image/png"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"github.com/hajimehoshi/ebiten/v2"
)

// spriteAsset stores a loaded sprite with all its frames
type SpriteAsset struct {
	Name       string
	Width      int
	Height     int
	XOrigin    int
	YOrigin    int
	FrameCount int
	Frames     []*ebiten.Image
	BBox       BBoxDef
	ColKind    int
}

type BBoxDef struct {
	Left, Right, Top, Bottom int
}

// assetManager handles loading and caching of all game assets
type AssetManager struct {
	mu sync.RWMutex

	basePath    string
	sprites     map[string]*SpriteAsset
	backgrounds map[string]*ebiten.Image
	// sound assets are managed by AudioManager

	// metadata loaded from JSON manifests
	spriteMeta     []SpriteManifest
	backgroundMeta []BackgroundManifest
	soundMeta      []SoundManifest
}

// jSON manifest types (matching the extract tool output)
type SpriteManifest struct {
	Name       string   `json:"Name"`
	Width      int      `json:"Width"`
	Height     int      `json:"Height"`
	XOrigin    int      `json:"XOrigin"`
	YOrigin    int      `json:"YOrigin"`
	FrameCount int      `json:"FrameCount"`
	FramePaths []string `json:"FramePaths"`
	ColKind    int      `json:"ColKind"`
	BBox       struct {
		Left   int `json:"Left"`
		Right  int `json:"Right"`
		Top    int `json:"Top"`
		Bottom int `json:"Bottom"`
	} `json:"BBox"`
}

type BackgroundManifest struct {
	Name       string `json:"Name"`
	ImagePath  string `json:"ImagePath"`
	IsTileset  bool   `json:"IsTileset"`
	TileWidth  int    `json:"TileWidth"`
	TileHeight int    `json:"TileHeight"`
	Width      int    `json:"Width"`
	Height     int    `json:"Height"`
}

type SoundManifest struct {
	Name      string  `json:"Name"`
	FileName  string  `json:"FileName"`
	Extension string  `json:"Extension"`
	Volume    float64 `json:"Volume"`
	Pan       float64 `json:"Pan"`
}

func NewAssetManager() *AssetManager {
	return &AssetManager{
		sprites:     make(map[string]*SpriteAsset),
		backgrounds: make(map[string]*ebiten.Image),
	}
}

// setBasePath sets the root directory for assets
func (am *AssetManager) SetBasePath(path string) {
	am.basePath = path
}

// loadManifests loads the JSON manifests generated by the extract tool
func (am *AssetManager) LoadManifests() error {
	dataDir := filepath.Join(am.basePath, "data")

	// load sprite manifest
	if err := loadJSON(filepath.Join(dataDir, "sprites.json"), &am.spriteMeta); err != nil {
		return fmt.Errorf("loading sprite manifest: %w", err)
	}

	// load background manifest
	if err := loadJSON(filepath.Join(dataDir, "backgrounds.json"), &am.backgroundMeta); err != nil {
		return fmt.Errorf("loading background manifest: %w", err)
	}

	// load sound manifest
	if err := loadJSON(filepath.Join(dataDir, "sounds.json"), &am.soundMeta); err != nil {
		return fmt.Errorf("loading sound manifest: %w", err)
	}

	fmt.Printf("Loaded manifests: %d sprites, %d backgrounds, %d sounds\n",
		len(am.spriteMeta), len(am.backgroundMeta), len(am.soundMeta))
	return nil
}

// loadSprite loads a sprite by name (lazy loading)
func (am *AssetManager) LoadSprite(name string) (*SpriteAsset, error) {
	am.mu.RLock()
	if s, ok := am.sprites[name]; ok {
		am.mu.RUnlock()
		return s, nil
	}
	am.mu.RUnlock()

	// find in manifest
	var meta *SpriteManifest
	for i := range am.spriteMeta {
		if am.spriteMeta[i].Name == name {
			meta = &am.spriteMeta[i]
			break
		}
	}
	if meta == nil {
		return nil, fmt.Errorf("sprite '%s' not found in manifest", name)
	}

	// load all frames
	frames := make([]*ebiten.Image, len(meta.FramePaths))
	for i, fp := range meta.FramePaths {
		imgFile := filepath.Base(fp)
		fullPath := filepath.Join(am.basePath, "sprites", imgFile)
		img, err := loadPNG(fullPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "WARNING: missing frame %s for sprite %s\n", imgFile, name)
			// create a placeholder transparent image
			frames[i] = ebiten.NewImage(meta.Width, meta.Height)
			continue
		}
		frames[i] = ebiten.NewImageFromImage(img)
	}

	sprite := &SpriteAsset{
		Name:       name,
		Width:      meta.Width,
		Height:     meta.Height,
		XOrigin:    meta.XOrigin,
		YOrigin:    meta.YOrigin,
		FrameCount: meta.FrameCount,
		Frames:     frames,
		BBox: BBoxDef{
			Left:   meta.BBox.Left,
			Right:  meta.BBox.Right,
			Top:    meta.BBox.Top,
			Bottom: meta.BBox.Bottom,
		},
		ColKind: meta.ColKind,
	}

	am.mu.Lock()
	am.sprites[name] = sprite
	am.mu.Unlock()

	return sprite, nil
}

// getSprite returns a cached sprite or loads it on demand
func (am *AssetManager) GetSprite(name string) *SpriteAsset {
	am.mu.RLock()
	if s, ok := am.sprites[name]; ok {
		am.mu.RUnlock()
		return s
	}
	am.mu.RUnlock()

	s, err := am.LoadSprite(name)
	if err != nil {
		return nil
	}
	return s
}

// loadBackground loads a background image by name
func (am *AssetManager) LoadBackground(name string) (*ebiten.Image, error) {
	am.mu.RLock()
	if bg, ok := am.backgrounds[name]; ok {
		am.mu.RUnlock()
		return bg, nil
	}
	am.mu.RUnlock()

	// find in manifest
	var meta *BackgroundManifest
	for i := range am.backgroundMeta {
		if am.backgroundMeta[i].Name == name {
			meta = &am.backgroundMeta[i]
			break
		}
	}
	if meta == nil {
		return nil, fmt.Errorf("background '%s' not found in manifest", name)
	}

	imgFile := filepath.Base(meta.ImagePath)
	fullPath := filepath.Join(am.basePath, "backgrounds", imgFile)
	img, err := loadPNG(fullPath)
	if err != nil {
		return nil, fmt.Errorf("loading background image %s: %w", imgFile, err)
	}

	eImg := ebiten.NewImageFromImage(img)

	am.mu.Lock()
	am.backgrounds[name] = eImg
	am.mu.Unlock()

	return eImg, nil
}

// getBackground returns a cached background or loads it on demand
func (am *AssetManager) GetBackground(name string) *ebiten.Image {
	am.mu.RLock()
	if bg, ok := am.backgrounds[name]; ok {
		am.mu.RUnlock()
		return bg
	}
	am.mu.RUnlock()

	bg, err := am.LoadBackground(name)
	if err != nil {
		return nil
	}
	return bg
}

// preloadSprites loads all sprites into memory (for faster runtime)
func (am *AssetManager) PreloadSprites() int {
	loaded := 0
	for _, meta := range am.spriteMeta {
		if _, err := am.LoadSprite(meta.Name); err == nil {
			loaded++
		}
	}
	return loaded
}

// preloadBackgrounds loads all backgrounds into memory
func (am *AssetManager) PreloadBackgrounds() int {
	loaded := 0
	for _, meta := range am.backgroundMeta {
		if _, err := am.LoadBackground(meta.Name); err == nil {
			loaded++
		}
	}
	return loaded
}

// getSpriteNames returns all known sprite names
func (am *AssetManager) GetSpriteNames() []string {
	names := make([]string, len(am.spriteMeta))
	for i, m := range am.spriteMeta {
		names[i] = m.Name
	}
	return names
}

// helper: load a PNG file into image.Image
func loadPNG(path string) (image.Image, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	// try PNG first, fall back to generic decode
	img, err := png.Decode(f)
	if err != nil {
		f.Seek(0, 0)
		img, _, err = image.Decode(f)
		if err != nil {
			return nil, fmt.Errorf("decoding image %s: %w", path, err)
		}
	}
	return img, nil
}

// helper: load JSON file into a value
func loadJSON(path string, v interface{}) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, v)
}

// getSoundMeta returns sound metadata for the audio manager
func (am *AssetManager) GetSoundMeta() []SoundManifest {
	return am.soundMeta
}

// getBasePath returns the asset base path
func (am *AssetManager) GetBasePath() string {
	return am.basePath
}

// helper to strip file extension
func stripExt(name string) string {
	ext := filepath.Ext(name)
	return strings.TrimSuffix(name, ext)
}

// bitmap font support

// bMFontGlyph stores metrics for one glyph in a bitmap font
type BMFontGlyph struct {
	Char   rune
	X, Y   int // position in the font atlas
	W, H   int // glyph dimensions
	Shift  int // advance width (how far to move cursor)
	Offset int // x offset when drawing
}

// bMFont represents a loaded bitmap font
type BMFont struct {
	Name   string
	Atlas  *ebiten.Image
	Glyphs map[rune]*BMFontGlyph
}

// drawText draws a string using this bitmap font at (x, y) with the given color
func (f *BMFont) DrawText(screen *ebiten.Image, text string, x, y float64, clr [3]uint8) {
	if f.Atlas == nil {
		return
	}
	dx := x
	for _, ch := range text {
		g, ok := f.Glyphs[ch]
		if !ok {
			dx += 8 // default spacing for unknown chars
			continue
		}

		// sub-image the glyph from the atlas
		rect := image.Rect(g.X, g.Y, g.X+g.W, g.Y+g.H)
		sub := f.Atlas.SubImage(rect).(*ebiten.Image)

		op := &ebiten.DrawImageOptions{}
		op.GeoM.Translate(dx+float64(g.Offset), y)
		// tint with color
		r := float32(clr[0]) / 255.0
		gr := float32(clr[1]) / 255.0
		b := float32(clr[2]) / 255.0
		op.ColorScale.Scale(r, gr, b, 1)
		screen.DrawImage(sub, op)

		dx += float64(g.Shift)
	}
}

// drawTextScaled draws text using a scale factor (useful for compact UI labels).
func (f *BMFont) DrawTextScaled(screen *ebiten.Image, text string, x, y, scale float64, clr [3]uint8) {
	if f.Atlas == nil {
		return
	}
	if scale <= 0 {
		scale = 1
	}
	dx := x
	for _, ch := range text {
		g, ok := f.Glyphs[ch]
		if !ok {
			dx += 8 * scale
			continue
		}

		rect := image.Rect(g.X, g.Y, g.X+g.W, g.Y+g.H)
		sub := f.Atlas.SubImage(rect).(*ebiten.Image)

		op := &ebiten.DrawImageOptions{}
		op.GeoM.Scale(scale, scale)
		op.GeoM.Translate(dx+float64(g.Offset)*scale, y)
		r := float32(clr[0]) / 255.0
		gr := float32(clr[1]) / 255.0
		b := float32(clr[2]) / 255.0
		op.ColorScale.Scale(r, gr, b, 1)
		screen.DrawImage(sub, op)

		dx += float64(g.Shift) * scale
	}
}

// loadBMFont loads a bitmap font from a JSON glyph definition and PNG atlas
func (am *AssetManager) LoadBMFont(name, jsonPath, pngPath string) (*BMFont, error) {
	// load the atlas image
	img, err := loadPNG(pngPath)
	if err != nil {
		return nil, fmt.Errorf("loading font atlas %s: %w", pngPath, err)
	}

	atlas := ebiten.NewImageFromImage(img)

	// parse glyph data from JSON
	type glyphJSON struct {
		Char   int `json:"char"`
		X      int `json:"x"`
		Y      int `json:"y"`
		W      int `json:"w"`
		H      int `json:"h"`
		Shift  int `json:"shift"`
		Offset int `json:"offset"`
	}
	type fontJSON struct {
		Name   string      `json:"name"`
		Size   int         `json:"size"`
		Glyphs []glyphJSON `json:"glyphs"`
	}

	data, err := os.ReadFile(jsonPath)
	if err != nil {
		return nil, fmt.Errorf("reading font JSON %s: %w", jsonPath, err)
	}
	var fd fontJSON
	if err := json.Unmarshal(data, &fd); err != nil {
		return nil, fmt.Errorf("parsing font JSON: %w", err)
	}

	font := &BMFont{
		Name:   name,
		Atlas:  atlas,
		Glyphs: make(map[rune]*BMFontGlyph),
	}

	for _, g := range fd.Glyphs {
		font.Glyphs[rune(g.Char)] = &BMFontGlyph{
			Char:   rune(g.Char),
			X:      g.X,
			Y:      g.Y,
			W:      g.W,
			H:      g.H,
			Shift:  g.Shift,
			Offset: g.Offset,
		}
	}

	fmt.Printf("Loaded bitmap font '%s': %d glyphs\n", name, len(font.Glyphs))
	return font, nil
}
